apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotwit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gotwit-operator
  template:
    metadata:
      labels:
        name: gotwit-operator
    spec:
      serviceAccountName: gotwit-operator
      containers:
        - name: gotwit-operator
          # Replace this with the built image name
          image: quay.io/pratikmahajan/gotwt-operator:lat-2
          command:
          - gotwit-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gotwit-operator"
